package io.virinchi.yatra.Service;

import io.virinchi.yatra.Dto.AirlineRequest;
import io.virinchi.yatra.Dto.BookingRequest;
import io.virinchi.yatra.Dto.FlightRequest;
import io.virinchi.yatra.Dto.SeedResponse;
import io.virinchi.yatra.Exception.ConflictException;
import io.virinchi.yatra.Model.Airline;
import io.virinchi.yatra.Model.Booking;
import io.virinchi.yatra.Model.Destination;
import io.virinchi.yatra.Model.Flight;
import io.virinchi.yatra.Model.Passenger;
import io.virinchi.yatra.Model.Payment;
import io.virinchi.yatra.Model.Seat;
import io.virinchi.yatra.Model.Ticket;
import io.virinchi.yatra.Model.User;
import io.virinchi.yatra.Repository.AirlineRepository;
import io.virinchi.yatra.Repository.BookingRepository;
import io.virinchi.yatra.Repository.DestinationRepository;
import io.virinchi.yatra.Repository.FlightRepository;
import io.virinchi.yatra.Repository.PassengerRepository;
import io.virinchi.yatra.Repository.PaymentRepository;
import io.virinchi.yatra.Repository.SeatRepository;
import io.virinchi.yatra.Repository.TicketRepository;
import io.virinchi.yatra.Repository.UserRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

/**
 * Roadmap Phase 7 — the demo data seeder, and the reset that makes it re-runnable.
 *
 * <h2>What it writes, and where the numbers come from</h2>
 *
 * <p><b>The frontend mock is the source of the content, not this class's
 * imagination.</b> The four carriers, the eleven airports, the ten-account roster,
 * the flight numbers/routes/fares and the eight bookings with their PNRs, ticket
 * numbers and eSewa transaction ids are all transcribed from
 * {@code assets/js/mock-data.js}, {@code admin-flights.js} and
 * {@code admin-bookings.js}. The pages already render those exact records in mock
 * mode, so a seeded database answers the real API with data those pages recognise —
 * which is the same "the frontend is the contract" call the airline, flight and
 * booking modules made. Six extra flights are added on top of the mock's six so the
 * admin table's pagination is visibly exercised rather than theoretical.
 *
 * <p><b>It reuses the real services rather than inserting rows.</b> Airlines go
 * through {@link AirlineService#createAirline} (so the IATA rules and the R8 logo
 * write apply), flights through {@link FlightService#createFlight} (so the seat map
 * is generated by the one piece of code that knows how to generate it), and bookings
 * through {@link BookingService#createBooking} (so the seeded bookings hold their
 * seats through the same atomic claim a customer's booking uses). If any of those
 * paths breaks, seeding fails loudly — which is the point: a seeder that bypasses the
 * services would happily manufacture data the API itself would reject.
 *
 * <h2>Re-runnable, and honest about how</h2>
 *
 * <p>{@link #seed()} is <b>not</b> additive on top of the last seed: it refuses with
 * 409 {@code ALREADY_SEEDED} when the marker is already present, because seeding
 * twice would double every flight's booked seats and mint a second set of payments
 * and tickets (both {@code unique NOT NULL} on {@code booking_id}). The re-run path is
 * therefore explicit: {@link #reset()} then {@link #seed()}.
 *
 * <p>That is exactly the operation the standards doc left open in §7 question 6 —
 * whether seeded bookings may vanish completely. R4's rule is untouched: a paid,
 * ticketed booking is still a sale record and the admin APIs still answer 409 and say
 * "cancel it instead". A <b>reset</b> is the separate, deliberately destructive
 * operation that removes rows carrying the seed marker, and only those.
 *
 * <h2>Why the marker column exists</h2>
 *
 * <p>Every row this class creates carries {@code seeded = true} (see
 * {@code Model/Airline} for the marker's own note). Without it a reset would have to
 * guess from natural keys — and deleting "everything whose flight number is U4 951"
 * would take an admin's own flight with it if they happened to type that number.
 * The marker is also what the mock already models: its demo bookings carry
 * {@code _seed: true}, and that flag is what makes the mock's trash icon appear on
 * demo rows only.
 *
 * <h2>What a reset deliberately keeps</h2>
 *
 * <ul>
 *   <li><b>Destinations.</b> Airports are reference data the whole app needs, not
 *       demo content; a reset that deleted them would break every hand-made flight's
 *       route and the wizard's airport lookup.</li>
 *   <li><b>A seeded airline or user that your own rows still reference.</b> Reported
 *       in {@link SeedResponse#kept()} with the reason, and left in place — a reset
 *       removes the demo data, not your work.</li>
 * </ul>
 */
@Service
@Slf4j
public class SeedService {

    /**
     * The demo credential, hashed with BCrypt for the nine seeded <b>customers</b>.
     *
     * <p>Seeded accounts need a real hash or the panel cannot be signed into on a
     * freshly seeded database, and a known demo password is the point of demo data. It
     * is a documented, local-only credential for an academic demo; it is not a secret,
     * and nothing here implies production use. Change it here and the seeded customer
     * logins change with it.
     */
    private static final String DEMO_PASSWORD = "Yatra@123";

    /**
     * The administrator's own credential — {@code admin@gmail.com} with this password.
     *
     * <p>Deliberately <b>not</b> {@link #DEMO_PASSWORD}. The author asked for the single
     * administrator to be {@code admin@gmail.com / admin} (2026-09-18, resolving the
     * standards doc's open question 8), and two constants are honest here because they
     * answer two different questions: "the demo roster's shared password" and "the one
     * privileged account". A per-role split also keeps the scope of the change to what
     * was asked for — the nine customers' documented shared password is untouched, so
     * the Postman customer sign-in and every existing demo instruction still hold.
     *
     * <p><b>The length asymmetry is intended.</b> Five characters is below the
     * <b>signup</b> minimum ({@code RegisterRequest}'s {@code @Size(min = 8)}), while
     * {@link io.virinchi.yatra.Dto.LoginRequest} has no length rule at all — so this
     * password can be <i>seeded and signed in with</i>, but never created through the
     * public signup form. Do not "fix" it by relaxing the signup rule: that rule is the
     * one protecting real registrations, and this is a seeded demo account.
     */
    private static final String ADMIN_PASSWORD = "admin";

    private static final String CONFIRMED = "CONFIRMED";
    private static final String CANCELLED = "CANCELLED";
    private static final String PAID = "Paid";
    private static final String REFUNDED = "Refunded";
    private static final String SUCCESS = "SUCCESS";
    private static final String ACTIVE = "Active";

    /* ------------------------------------------------------------------ *
     *  The seed content — transcribed from the frontend's mock data        *
     * ------------------------------------------------------------------ */

    /** Mirrors {@code mock-data.js} → {@code SEED_AIRLINES} (the roster is 4, not 5 — Summit Air was trimmed). */
    private record AirlineSeed(String name, String iata, String description, String logoFile) {
    }

    private static final List<AirlineSeed> AIRLINES = List.of(
            new AirlineSeed("Buddha Air", "U4",
                    "Nepal's largest domestic airline by fleet and destinations, operating ATR 42/72 aircraft.",
                    "airline-buddha.jpg"),
            new AirlineSeed("Yeti Airlines", "YT",
                    "Major domestic carrier connecting Kathmandu with Pokhara and other regional airports.",
                    "airline-yeti.jpg"),
            new AirlineSeed("Shree Airlines", "S3",
                    "Operates domestic routes and helicopter services across Nepal.",
                    "airline-shree.svg"),
            new AirlineSeed("Sita Air", "ST",
                    "Domestic airline serving scheduled and charter flights with Dornier and ATR aircraft.",
                    "airline-sita.jpeg"));

    /**
     * Mirrors {@code mock-data.js} → {@code SEED_DESTINATIONS}.
     *
     * <p>{@code imageUrl} is left empty on purpose: rule 3 keeps destination images on
     * Cloudinary, where the column holds only {@code secure_url} + {@code public_id},
     * and Phase 8 owns that upload. Copying the mock's local asset paths here would
     * put static-file paths in a column the brief says must hold a Cloudinary URL.
     */
    private record DestinationSeed(String city, String code, String airport, String description) {
    }

    private static final List<DestinationSeed> DESTINATIONS = List.of(
            new DestinationSeed("Kathmandu", "KTM", "Tribhuvan International Airport",
                    "Nepal's capital and the hub of the domestic network — nearly every route connects here."),
            new DestinationSeed("Pokhara", "PKR", "Pokhara International Airport",
                    "Gateway to the Annapurnas and Phewa Lake — the busiest tourist route in the country."),
            new DestinationSeed("Biratnagar", "BIR", "Biratnagar Airport",
                    "Eastern metropolis and industrial hub of the Terai plains."),
            new DestinationSeed("Bhairahawa", "BWA", "Gautam Buddha International Airport",
                    "Home of Lumbini, the birthplace of Buddha — the newest international gateway."),
            new DestinationSeed("Nepalgunj", "KEP", "Nepalgunj Airport",
                    "Western Terai hub and the jumping-off point for remote western Nepal."),
            new DestinationSeed("Bharatpur", "BHR", "Bharatpur Airport",
                    "Chitwan city serving Sauraha and the national-park safari circuit."),
            new DestinationSeed("Bhadrapur", "BDP", "Bhadrapur Airport",
                    "Eastern gateway to Ilam's tea gardens and the taplejung trailheads."),
            new DestinationSeed("Janakpur", "JKR", "Janakpur Airport",
                    "Historic Mithila city and pilgrimage centre of Sita Janaki."),
            new DestinationSeed("Simara", "SIM", "Simara Airport",
                    "Bara district airport serving the industrial corridor south of Kathmandu."),
            new DestinationSeed("Dhangadhi", "DHI", "Dhangadhi Airport",
                    "Far-western commercial hub and gateway to Sudurpashchim."),
            new DestinationSeed("Tumlingtar", "TMI", "Tumlingtar Airport",
                    "Eastern hill-town airport on the Arun valley route."));

    /** Mirrors {@code mock-data.js} → {@code SEED_USERS}, with the mock's own registration dates as day offsets. */
    private record UserSeed(String name, String email, String phone, String role, String status, int daysAgo) {
    }

    private static final List<UserSeed> USERS = List.of(
            new UserSeed("Dikshya Ghising", "admin@gmail.com", "9800000001", "ADMIN", ACTIVE, 47),
            new UserSeed("Anju Karki", "anju.karki@example.com", "9841234567", "USER", ACTIVE, 16),
            new UserSeed("Bikash Shrestha", "bikash.s@example.com", "9818765432", "USER", ACTIVE, 12),
            new UserSeed("Sanjay Thapa Magar", "sanjay.tm@example.com", "9801122334", "USER", "Inactive", 11),
            new UserSeed("Prakriti Rai", "prakriti.rai@example.com", "9856234781", "USER", ACTIVE, 9),
            new UserSeed("Nirmala Gurung", "nirmala.g@example.com", "9845612309", "USER", ACTIVE, 8),
            new UserSeed("Dipesh Neupane", "dipesh.n@example.com", "9861250974", "USER", ACTIVE, 7),
            new UserSeed("Sarita Lamichhane", "sarita.l@example.com", "9849056172", "USER", "Inactive", 6),
            new UserSeed("Kabin Bhandari", "kabin.b@example.com", "9807341285", "USER", ACTIVE, 5),
            new UserSeed("Manish Pokhrel", "manish.p@example.com", "9812345678", "USER", ACTIVE, 4));

    /**
     * The mock's six flights, then six more across the same carriers.
     *
     * <p>{@code daysFromToday} replaces the mock's fixed September dates so the data is
     * never stale: the flights span yesterday to six days out, every run.
     */
    private record FlightSeed(String no, String iata, String from, String to, int daysFromToday,
                              String dep, String arr, String aircraft, String fare, int seats) {
    }

    private static final List<FlightSeed> FLIGHTS = List.of(
            new FlightSeed("U4 951", "U4", "KTM", "PKR", 0, "06:50", "07:35", "ATR 72", "8299.99", 70),
            new FlightSeed("YT 958", "YT", "KTM", "PKR", 0, "09:55", "10:40", "ATR 72", "8449.99", 70),
            new FlightSeed("S3 507", "S3", "KTM", "BIR", 1, "11:35", "12:20", "CRJ 700", "8899.99", 78),
            new FlightSeed("ST 221", "ST", "KTM", "KEP", 1, "12:50", "13:45", "Dornier 228", "9199.99", 19),
            new FlightSeed("U4 953", "U4", "KTM", "BWA", 2, "15:10", "16:00", "ATR 72", "8799.99", 70),
            new FlightSeed("YT 962", "YT", "PKR", "KTM", 2, "17:25", "18:10", "ATR 42", "8299.99", 46),
            new FlightSeed("U4 961", "U4", "PKR", "KTM", 3, "07:20", "08:05", "ATR 72", "8399.99", 70),
            new FlightSeed("YT 964", "YT", "KTM", "BHR", 3, "10:15", "10:50", "ATR 42", "7499.99", 46),
            new FlightSeed("S3 511", "S3", "KTM", "BDP", 4, "13:05", "13:55", "CRJ 700", "9599.99", 78),
            new FlightSeed("ST 231", "ST", "KTM", "JKR", 4, "14:20", "15:00", "Dornier 228", "8699.99", 19),
            new FlightSeed("U4 957", "U4", "KTM", "DHI", 5, "16:40", "17:45", "ATR 72", "11499.99", 70),
            new FlightSeed("YT 966", "YT", "KTM", "TMI", 6, "08:40", "09:30", "ATR 42", "9299.99", 46));

    /** A passenger on a seeded booking. */
    private record PassengerSeed(String title, String firstName, String lastName, String type) {
    }

    /**
     * The mock's eight bookings, keyed by the email of the account that owns them.
     *
     * <p>{@code daysAgo} is the booking's age — two of them are today's, which is what
     * makes a "Today's Bookings" tile (Phase 13) show a number rather than a zero.
     *
     * <p>The mock's per-booking amounts used fare-class deltas (a Y-Class seat at
     * {@code 13299.99} against a base fare of {@code 8449.99}). Those deltas belong to
     * the fare-class phase, so a seeded booking totals {@code flight.fare × passengers}
     * — the same rule {@code BookingService} applies to every real booking. The
     * consequence, stated rather than hidden: the seeded totals do not equal the mock's
     * class-priced figures, and they will match once the deltas exist.
     */
    private record BookingSeed(String pnr, String ticketNo, String txnId, String email,
                               String status, String paymentStatus, String fareClass, boolean refundable,
                               int daysAgo, List<PassengerSeed> passengers) {
    }

    private static final List<BookingSeed> BOOKINGS = List.of(
            new BookingSeed("YTRA26", "784-244829135701", "9A48291357", "anju.karki@example.com",
                    CONFIRMED, PAID, "E Class", false, 4,
                    List.of(new PassengerSeed("Ms", "Anju", "Karki", "ADT"),
                            new PassengerSeed("Mr", "Rohan", "Karki", "CHD"))),
            new BookingSeed("YTRA48", "784-246715398202", "9A67153982", "bikash.s@example.com",
                    CONFIRMED, PAID, "Y Class", true, 4,
                    List.of(new PassengerSeed("Mr", "Bikash", "Shrestha", "ADT"))),
            new BookingSeed("YTRA71", "784-249024671503", "9A90246715", "sanjay.tm@example.com",
                    CANCELLED, REFUNDED, "D Class", false, 3,
                    List.of(new PassengerSeed("Mr", "Sanjay", "Thapa Magar", "ADT"),
                            new PassengerSeed("Mrs", "Mina", "Thapa Magar", "ADT"),
                            new PassengerSeed("Miss", "Sujata", "Thapa Magar", "CHD"))),
            new BookingSeed("YTRA33", "784-241159802674", "9A11598026", "prakriti.rai@example.com",
                    CONFIRMED, PAID, "E Class", false, 2,
                    List.of(new PassengerSeed("Ms", "Prakriti", "Rai", "ADT"))),
            new BookingSeed("YTRA59", "784-245538114095", "9A55381140", "nirmala.g@example.com",
                    CONFIRMED, PAID, "C Class", false, 2,
                    List.of(new PassengerSeed("Mrs", "Nirmala", "Gurung", "ADT"),
                            new PassengerSeed("Mr", "Tenzing", "Gurung", "ADT"),
                            new PassengerSeed("Miss", "Anisha", "Gurung", "CHD"),
                            new PassengerSeed("Master", "Prabal", "Gurung", "CHD"))),
            new BookingSeed("YTRA84", "784-243367412956", "9A33674129", "dipesh.n@example.com",
                    CONFIRMED, PAID, "A Class", true, 1,
                    List.of(new PassengerSeed("Mr", "Dipesh", "Neupane", "ADT"))),
            new BookingSeed("YTRA92", "784-247741290357", "9A77412903", "sarita.l@example.com",
                    CONFIRMED, PAID, "B Class", false, 0,
                    List.of(new PassengerSeed("Mrs", "Sarita", "Lamichhane", "ADT"),
                            new PassengerSeed("Mr", "Hari", "Lamichhane", "ADT"))),
            new BookingSeed("YTRA15", "784-244209357118", "9A42093571", "kabin.b@example.com",
                    CONFIRMED, PAID, "Y Class", true, 0,
                    List.of(new PassengerSeed("Mr", "Kabin", "Bhandari", "ADT"))));

    /** Which seeded booking rides on which seeded flight (the mock's own pairing). */
    private static final List<String> BOOKING_FLIGHTS = List.of(
            "U4 951", "YT 958", "S3 507", "ST 221", "U4 953", "YT 962", "U4 951", "S3 507");

    /* ------------------------------------------------------------------ *
     *  Collaborators                                                      *
     * ------------------------------------------------------------------ */

    private final AirlineService airlineService;
    private final FlightService flightService;
    private final BookingService bookingService;
    private final DestinationRepository destinations;
    private final AirlineRepository airlines;
    private final FlightRepository flights;
    private final UserRepository users;
    private final BookingRepository bookings;
    private final PassengerRepository passengers;
    private final PaymentRepository payments;
    private final TicketRepository tickets;
    private final SeatRepository seats;
    private final PasswordEncoder passwordEncoder;

    public SeedService(AirlineService airlineService,
                       FlightService flightService,
                       BookingService bookingService,
                       DestinationRepository destinations,
                       AirlineRepository airlines,
                       FlightRepository flights,
                       UserRepository users,
                       BookingRepository bookings,
                       PassengerRepository passengers,
                       PaymentRepository payments,
                       TicketRepository tickets,
                       SeatRepository seats,
                       PasswordEncoder passwordEncoder) {
        this.airlineService = airlineService;
        this.flightService = flightService;
        this.bookingService = bookingService;
        this.destinations = destinations;
        this.airlines = airlines;
        this.flights = flights;
        this.users = users;
        this.bookings = bookings;
        this.passengers = passengers;
        this.payments = payments;
        this.tickets = tickets;
        this.seats = seats;
        this.passwordEncoder = passwordEncoder;
    }

    /* ------------------------------------------------------------------ *
     *  Seed                                                               *
     * ------------------------------------------------------------------ */

    /**
     * Creates the demo dataset — airlines, airports, accounts, flights, bookings,
     * payments and tickets, in one transaction.
     *
     * @throws ConflictException 409 {@code ALREADY_SEEDED} — the marker is already
     *                           present; reset first
     */
    @Transactional
    public SeedResponse seed() {
        requireNotSeeded();

        LocalDate today = LocalDate.now();
        LocalDateTime now = LocalDateTime.now();

        int destinationsCreated = seedDestinations();
        Map<String, Airline> airlinesByIata = seedAirlines();
        Map<String, User> usersByEmail = seedUsers(now);
        Map<String, Flight> flightsByNo = seedFlights(airlinesByIata, today);
        Map<String, Integer> bookingCounts = seedBookings(flightsByNo, usersByEmail, now);

        Map<String, Integer> counts = new LinkedHashMap<>();
        counts.put("airlines", airlinesByIata.size());
        // "In place", not "inserted": a destination or carrier that already existed (a
        // re-seed, or an airport the admin added) still counts, because what the counts
        // describe is the dataset the seed guarantees, not how much work it had to do.
        // Otherwise a second seed after a reset — where the airports were deliberately
        // kept — would report zero destinations that it had just finished using.
        counts.put("destinations", DESTINATIONS.size());
        counts.put("users", usersByEmail.size());
        counts.put("flights", flightsByNo.size());
        counts.put("seats", flightsByNo.values().stream().mapToInt(Flight::getSeatCapacity).sum());
        counts.put("bookings", bookingCounts.get("bookings"));
        counts.put("passengers", bookingCounts.get("passengers"));
        counts.put("payments", bookingCounts.get("bookings"));
        counts.put("tickets", bookingCounts.get("bookings"));

        log.info("Demo seed applied: {} airlines, {} destinations ({} created), {} users, {} flights, {} bookings",
                counts.get("airlines"), counts.get("destinations"), destinationsCreated,
                counts.get("users"), counts.get("flights"), counts.get("bookings"));

        return new SeedResponse(
                "SEED",
                "Demo data created. Admin sign-in: admin@gmail.com (password: the documented admin credential). "
                        + "Destinations are left un-marked, so a reset keeps them.",
                counts,
                List.of());
    }

    /**
     * Refuses a second seed. Guarded by the marker, not by a count of flights, so it
     * stays correct once the demo's own numbers have moved on.
     */
    private void requireNotSeeded() {
        boolean alreadySeeded = !airlines.findBySeededTrue().isEmpty()
                || !flights.findBySeededTrue().isEmpty()
                || !users.findBySeededTrue().isEmpty()
                || !bookings.findBySeededTrue().isEmpty();

        if (alreadySeeded) {
            throw new ConflictException("ALREADY_SEEDED",
                    "The demo data is already seeded. Call POST /api/admin/reset first — seeding twice would "
                            + "double every flight's booked seats and mint a second payment and ticket per "
                            + "booking, which the unique keys on the booking row would then refuse anyway.");
        }
    }

    /**
     * Airports — find-or-create by code, so a destination the admin already added (or
     * a partial earlier run) does not collide with the {@code code} unique key.
     * Destinations carry no seed marker on purpose: see the class docs.
     */
    private int seedDestinations() {
        int created = 0;
        for (DestinationSeed seed : DESTINATIONS) {
            if (destinations.findByCode(seed.code()).isPresent()) {
                continue;
            }
            Destination destination = new Destination();
            destination.setCity(seed.city());
            destination.setCode(seed.code());
            destination.setAirport(seed.airport());
            destination.setDescription(seed.description());
            destination.setStatus(ACTIVE);
            destinations.save(destination);
            created++;
        }
        destinations.flush();
        return created;
    }

    /** Carriers, through the airline service — so the IATA uniqueness rule and the logo write both apply. */
    private Map<String, Airline> seedAirlines() {
        Map<String, Airline> byIata = new LinkedHashMap<>();

        for (AirlineSeed seed : AIRLINES) {
            Optional<Airline> existing = airlines.findByIata(seed.iata());
            if (existing.isPresent()) {
                // A hand-made carrier already owns this code: use it, do not mark it as
                // seed data, and do not overwrite it. Its flights still seed fine.
                byIata.put(seed.iata(), existing.get());
                continue;
            }

            Airline airline = airlineService.createAirline(new AirlineRequest(
                    seed.name(), seed.iata(), seed.description(), ACTIVE, logoDataUrl(seed.logoFile())));
            airline.setSeeded(true);
            byIata.put(seed.iata(), airline);
        }

        airlines.flush();
        return byIata;
    }

    /**
     * The account roster, with BCrypt hashes of the documented demo credential —
     * {@link #ADMIN_PASSWORD} for the administrator, {@link #DEMO_PASSWORD} for the rest.
     *
     * <p>Email is lower-cased before the lookup because {@code users.email} is
     * {@code utf8mb4_bin} and {@code UserService} lower-cases on registration —
     * matching its rule keeps the two paths agreeing on what "the same email" means.
     */
    private Map<String, User> seedUsers(LocalDateTime now) {
        Map<String, User> byEmail = new LinkedHashMap<>();
        String hash = passwordEncoder.encode(DEMO_PASSWORD);
        String adminHash = passwordEncoder.encode(ADMIN_PASSWORD);

        for (UserSeed seed : USERS) {
            String email = seed.email().toLowerCase(Locale.ROOT);
            Optional<User> existing = users.findByEmailIgnoreCase(email);
            if (existing.isPresent()) {
                byEmail.put(email, existing.get());
                continue;
            }

            User user = new User();
            user.setName(seed.name());
            user.setEmail(email);
            user.setPhone(seed.phone());
            /* The administrator is the one account with its own password (see
               ADMIN_PASSWORD) — every other seeded row shares DEMO_PASSWORD. */
            user.setPassword("ADMIN".equals(seed.role()) ? adminHash : hash);
            user.setRole(seed.role());
            user.setStatus(seed.status());
            user.setRegisteredAt(now.minusDays(seed.daysAgo()));
            user.setSeeded(true);
            users.save(user);
            byEmail.put(email, user);
        }

        users.flush();
        return byEmail;
    }

    /**
     * The flight list — through {@link FlightService#createFlight}, so each flight gets
     * its generated seat map from the one implementation that owns that rule.
     *
     * <p>{@code date} is set here (unlike the admin form, which has no date input): a
     * seeded flight should be findable by a date-filtered search, and the dates are
     * relative to today so the demo never goes stale.
     */
    private Map<String, Flight> seedFlights(Map<String, Airline> airlinesByIata, LocalDate today) {
        Map<String, Flight> byNo = new LinkedHashMap<>();

        for (FlightSeed seed : FLIGHTS) {
            Airline airline = airlinesByIata.get(seed.iata());
            if (airline == null) {
                throw new IllegalStateException(
                        "seed flight " + seed.no() + " names an airline that was not seeded: " + seed.iata());
            }

            Flight flight = flightService.createFlight(new FlightRequest(
                    seed.no(), airline.getId(), seed.from(), seed.to(),
                    today.plusDays(seed.daysFromToday()),
                    LocalTime.parse(seed.dep()), LocalTime.parse(seed.arr()), seed.aircraft(),
                    new BigDecimal(seed.fare()), seed.seats(), ACTIVE));
            flight.setSeeded(true);
            byNo.put(seed.no(), flight);
        }

        flights.flush();
        return byNo;
    }

    /**
     * The bookings, with their payment and ticket rows.
     *
     * <p>Each one is created by {@link BookingService#createBooking} — contact block,
     * passengers, and the seats they hold — and then moved to its seeded status. That
     * ordering matters: the seat claim is the same atomic UPDATE a customer's booking
     * goes through, so a seeded flight's {@code bookedSeats} is real from the first
     * second, and the mock's invented counts are no longer anywhere in the picture.
     *
     * <p>The cancelled/refunded booking keeps its seats, exactly as the admin page's
     * own cancel dialog promises ("Seats stay counted on the flight; the refund itself
     * is completed by the payments flow").
     */
    private Map<String, Integer> seedBookings(Map<String, Flight> flightsByNo,
                                              Map<String, User> usersByEmail,
                                              LocalDateTime now) {
        int passengerCount = 0;

        for (int index = 0; index < BOOKINGS.size(); index++) {
            BookingSeed seed = BOOKINGS.get(index);
            Flight flight = flightsByNo.get(BOOKING_FLIGHTS.get(index));
            if (flight == null) {
                throw new IllegalStateException("seed booking " + seed.pnr() + " names an unseeded flight");
            }

            User user = usersByEmail.get(seed.email().toLowerCase(Locale.ROOT));
            LocalDateTime createdAt = now.minusDays(seed.daysAgo()).withNano(0);

            Booking booking = bookingService.createBooking(
                    bookingRequest(seed, flight, createdAt), user == null ? null : user.getId());

            booking.setBookingStatus(seed.status());
            booking.setPaymentStatus(seed.paymentStatus());
            booking.setFareClass(seed.fareClass());
            booking.setRefundable(seed.refundable());
            booking.setCreatedAt(createdAt);
            booking.setSeeded(true);
            bookings.save(booking);

            payments.save(payment(booking, seed, createdAt));
            tickets.save(ticket(booking, seed, createdAt));
            passengerCount += seed.passengers().size();
        }

        bookings.flush();
        payments.flush();
        tickets.flush();

        Map<String, Integer> counts = new HashMap<>();
        counts.put("bookings", BOOKINGS.size());
        counts.put("passengers", passengerCount);
        return counts;
    }

    /**
     * The wizard's payload shape, built from a seed record — so a seeded booking
     * travels the exact request path {@code booking.js} uses. The pricing fields are
     * left null on purpose: {@code BookingService} ignores whatever the client sends
     * and computes the total from the flight row.
     */
    private BookingRequest bookingRequest(BookingSeed seed, Flight flight, LocalDateTime createdAt) {
        List<BookingRequest.Passenger> rows = new ArrayList<>();
        for (PassengerSeed passenger : seed.passengers()) {
            rows.add(new BookingRequest.Passenger(passenger.title(), passenger.firstName(), null,
                    passenger.lastName(), "Nepali", passenger.type(), null));
        }

        BookingRequest.Contact contact = new BookingRequest.Contact(
                seed.passengers().get(0).title(),
                seed.passengers().get(0).firstName(),
                null,
                seed.passengers().get(0).lastName(),
                seed.email(), contactPhone(seed.email()), "Self", "", true);

        BookingRequest.SelectedFlight selected = new BookingRequest.SelectedFlight(
                flight.getFlightNo(),
                flight.getOrigin() == null ? null : flight.getOrigin().getCode(),
                flight.getDestination() == null ? null : flight.getDestination().getCode(),
                flight.getFlightDate() == null ? null : flight.getFlightDate().toString(),
                null, null, null, seed.fareClass(), seed.refundable(), null, rows.size(), null);

        return new BookingRequest(contact, rows, selected, null);
    }

    /** The eSewa row the mock pairs with each booking; the amount must equal the booking's. */
    private Payment payment(Booking booking, BookingSeed seed, LocalDateTime createdAt) {
        Payment payment = new Payment();
        payment.setBooking(booking);
        payment.setMethod("eSewa");
        payment.setTxnId(seed.txnId());
        payment.setAmount(booking.getTotalAmount());
        payment.setStatus(REFUNDED.equalsIgnoreCase(seed.paymentStatus()) ? "REFUNDED" : SUCCESS);
        payment.setCreatedAt(createdAt);
        payment.setPaidAt(createdAt.plusMinutes(7));
        return payment;
    }

    /** A refunded booking's ticket is CANCELLED rather than ISSUED — the shape a refund leaves behind. */
    private Ticket ticket(Booking booking, BookingSeed seed, LocalDateTime createdAt) {
        Ticket ticket = new Ticket();
        ticket.setBooking(booking);
        ticket.setPnr(seed.pnr());
        ticket.setTicketNo(seed.ticketNo());
        ticket.setStatus(REFUNDED.equalsIgnoreCase(seed.paymentStatus()) ? CANCELLED : "ISSUED");
        ticket.setIssuedAt(createdAt.plusMinutes(8));
        return ticket;
    }

    /* ------------------------------------------------------------------ *
     *  Reset                                                              *
     * ------------------------------------------------------------------ */

    /**
     * Removes every row carrying the seed marker, in foreign-key order, and reports
     * what it kept.
     *
     * <p>This is the one place that hard-deletes a paid, ticketed booking. That is
     * deliberate and it is not a hole in R4's rule: the rule governs the admin APIs
     * (where a sale record is cancelled, never deleted), while a reset is a separate
     * demo-data operation that only ever touches rows this seeder created. The
     * alternative the standards doc rejected was relaxing the delete endpoint itself.
     *
     * <p>Deletion order follows the R4 probe: passengers, payments and tickets first
     * (with a flush), then the booking rows — because a deleted parent with a managed
     * child still pointing at it trips Hibernate's transient-reference check even with
     * {@code cascade = ALL} on the collection.
     */
    @Transactional
    public SeedResponse reset() {
        Map<String, Integer> counts = new LinkedHashMap<>();
        List<String> kept = new ArrayList<>();

        int[] bookingRows = deleteSeededBookings();
        Map<String, Integer> flightRows = deleteSeededFlights();
        int usersDeleted = deleteSeededUsers(kept);
        int airlinesDeleted = deleteSeededAirlines(kept);

        counts.put("airlines", airlinesDeleted);
        counts.put("destinations", 0);
        counts.put("users", usersDeleted);
        counts.put("flights", flightRows.get("flights"));
        counts.put("seats", flightRows.get("seats"));
        counts.put("bookings", bookingRows[0]);
        counts.put("passengers", bookingRows[1]);
        counts.put("payments", bookingRows[2]);
        counts.put("tickets", bookingRows[3]);

        log.info("Demo seed reset: {} bookings, {} flights, {} users, {} airlines removed",
                counts.get("bookings"), counts.get("flights"), counts.get("users"), counts.get("airlines"));

        return new SeedResponse(
                "RESET",
                kept.isEmpty()
                        ? "Seed data removed. Destinations were kept — airports are reference data, not demo data."
                        : "Seed data removed. Some seeded rows were kept because your own records still use them — "
                          + "see `kept`. Destinations were kept as reference data.",
                counts,
                kept);
    }

    /** @return {@code [bookings, passengers, payments, tickets]} deleted */
    private int[] deleteSeededBookings() {
        List<Booking> seeded = bookings.findBySeededTrue();
        int passengerCount = 0;
        int paymentCount = 0;
        int ticketCount = 0;

        for (Booking booking : seeded) {
            List<Passenger> rows = passengers.findByBookingId(booking.getId());
            passengerCount += rows.size();
            passengers.deleteAll(rows);

            Optional<Payment> payment = payments.findByBookingId(booking.getId());
            if (payment.isPresent()) {
                payments.delete(payment.get());
                paymentCount++;
            }

            Optional<Ticket> ticket = tickets.findByBookingId(booking.getId());
            if (ticket.isPresent()) {
                tickets.delete(ticket.get());
                ticketCount++;
            }
        }

        passengers.flush();
        payments.flush();
        tickets.flush();
        bookings.deleteAll(seeded);
        bookings.flush();

        return new int[]{seeded.size(), passengerCount, paymentCount, ticketCount};
    }

    /** @return {@code {flights, seats}} deleted — the seat map goes before its flight */
    private Map<String, Integer> deleteSeededFlights() {
        List<Flight> seeded = flights.findBySeededTrue();
        int seatRows = 0;

        for (Flight flight : seeded) {
            List<Seat> map = seats.findByFlightId(flight.getId());
            seatRows += map.size();
            seats.deleteAll(map);
        }

        seats.flush();
        flights.deleteAll(seeded);
        flights.flush();

        Map<String, Integer> counts = new HashMap<>();
        counts.put("flights", seeded.size());
        counts.put("seats", seatRows);
        return counts;
    }

    /**
     * Deletes the seeded accounts, except any that still owns a booking you made —
     * deleting one would take that booking with it through the {@code user_id} FK.
     */
    private int deleteSeededUsers(List<String> kept) {
        List<User> removable = new ArrayList<>();

        for (User user : users.findBySeededTrue()) {
            long ownBookings = bookings.countByUserId(user.getId());
            if (ownBookings > 0) {
                kept.add(user.getEmail() + " (seeded account kept — " + ownBookings
                        + " booking(s) of your own still reference it)");
            } else {
                removable.add(user);
            }
        }

        users.deleteAll(removable);
        users.flush();
        return removable.size();
    }

    /**
     * Same rule for carriers: one your own flight still uses stays, with the reason
     * reported — and it <b>keeps its marker</b>. That is deliberate: the row is still
     * seed data, it simply could not be removed yet, so the next reset will remove it
     * once the last record of yours using it is gone. Clearing the flag here would
     * quietly promote it to permanent fixture and a reset could never reach it again.
     */
    private int deleteSeededAirlines(List<String> kept) {
        List<Airline> removable = new ArrayList<>();

        for (Airline airline : airlines.findBySeededTrue()) {
            long remaining = flights.countByAirlineId(airline.getId());
            if (remaining > 0) {
                kept.add(airline.getName() + " (seeded airline kept — " + remaining
                        + " flight(s) of your own still use it)");
            } else {
                removable.add(airline);
            }
        }

        airlines.deleteAll(removable);
        airlines.flush();
        return removable.size();
    }

    /* ------------------------------------------------------------------ *
     *  Helpers                                                            *
     * ------------------------------------------------------------------ */

    /**
     * The airline logo read from the served assets and handed to the airline service as
     * a data URL — the one form its write path accepts (R8).
     *
     * <p>The files are the mock's own logo paths, so a seeded carrier renders exactly
     * what mock mode renders, and the bytes really do land in the {@code logo}
     * MEDIUMBLOB — the assignment's "images in the database" criterion, demonstrated
     * rather than just implemented.
     *
     * <p>Failures are tolerated: a missing or unreadable asset logs a warning and seeds
     * the airline without a logo, because demo data with one missing image is better
     * than a seed that cannot run.
     */
    private String logoDataUrl(String fileName) {
        try (InputStream stream = resource(fileName).getInputStream()) {
            byte[] bytes = stream.readAllBytes();
            return "data:" + contentType(fileName) + ";base64," + Base64.getEncoder().encodeToString(bytes);
        } catch (IOException | RuntimeException ex) {
            log.warn("Seed: could not read airline logo {} — seeding that airline without one ({})",
                    fileName, ex.getMessage());
            return null;
        }
    }

    private Resource resource(String fileName) {
        return new ClassPathResource("static/assets/imgs/" + fileName);
    }

    private static String contentType(String fileName) {
        String lower = fileName.toLowerCase(Locale.ROOT);
        if (lower.endsWith(".svg")) {
            return "image/svg+xml";
        }
        if (lower.endsWith(".png")) {
            return "image/png";
        }
        if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) {
            return "image/jpeg";
        }
        return "application/octet-stream";
    }

    /**
     * The seeded accounts' mobile numbers, mirrored from the mock's roster — the booking
     * needs a contact number and using the owner's own keeps the two views consistent.
     */
    private static String contactPhone(String email) {
        return USERS.stream()
                .filter(user -> user.email().equalsIgnoreCase(email))
                .map(UserSeed::phone)
                .findFirst()
                .orElse("9800000000");
    }
}
